routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::redirect('/backend', 'home');

Route::namespace('Auth')->prefix('backend')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::middleware('auth')->prefix('backend')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::prefix('profile')->group(function () {
        Route::GET('/', 'ProfileController@index')->name('profile.index');
        Route::GET('edit', 'ProfileController@edit')->name('profile.edit');
        Route::PUT('update', 'ProfileController@update')->name('profile.update');
    });

    Route::resource('brand', 'BrandController');
    Route::resource('car', 'CarController');

    Route::get('wishlist', 'WishlistController@index')->name('wishlist.index');

    Route::get('interested', 'InterestedController@index')->name('interested.index');

    Route::get('contact',  'ContactController@index')->name('contact.index');
    Route::get('contact/{contact}',  'ContactController@show')->name('contact.show');
    Route::get('contact/{contact}/edit',  'ContactController@edit')->name('contact.edit');

    Route::PATCH('sequence/up',   'SequenceController@up');
    Route::PATCH('sequence/down', 'SequenceController@down');

    Route::PATCH('wishlist/search',   'WishlistController@car_search_wishlist');
});

Route::view('/','index');
Route::view('/{any}','index');
Route::view('/{any}/{any1}', 'index');

resources/views/template/footer.blade.php
<!-- Footer -->
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>Footer
        </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-footer">
        <span class="navbar-text">
            &copy; {{ date('Y') }} <a href="{{ route('dashboard') }}"> CARCOMBINED MANAGEMENT</a>
        </span>
    </div>
</div>
<!-- /footer -->

resources/views/template/header.blade.php
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4>
                <i class="fa {{ $icon }} mr-2"></i>
                <span class="font-weight-semibold font f-24"> {!! $name !!} </span>
            </h4>
        </div>
    </div>
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            {{ Breadcrumbs::render() }}
        </div>
    </div>
</div>
<!-- /page header -->

resources/views/template/menu.blade.php
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
			<i class="icon-arrow-left8"></i>
		</a> <span class="font">เมนู</span>
        <a href="#" class="sidebar-mobile-expand">
			<i class="icon-screen-full"></i>
			<i class="icon-screen-normal"></i>
		</a>
    </div>
    <div class="sidebar-content">
        <div class="sidebar-user">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3">
                        <a href="{{ route('profile.index') }}">
                            <img src="/images/user.png" alt="" class="rounded-circle" width="50">
                        </a>
                    </div>
                    <div class="media-body">
                        <div class="media-title font-weight-semibold f-16"> {!! Auth::user()->name !!} </div>
                        <div class="font-size-xs opacity-10 mt-2">
                            <label class="badge badge-primary f-12">{!! Auth::user()->username !!}</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">
                <li class="nav-item">
                    <a href="{{ route('dashboard') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'dashboard') ? 'active' : '' }}">
                        <i class="icon-home2"></i>
                        <span class="font">
                            หน้าหลัก
                        </span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('brand.index') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'brand') ? 'active' : '' }}">
                        <i class="icon-steering-wheel"></i>
                        <span class="font">
                            ยี่ห้อรถ
                        </span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('car.index') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'car') ? 'active' : '' }}">
                        <i class="icon-car2"></i>
                        <span class="font">
                            ข้อมูลรถ
                        </span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('wishlist.index') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'wishlist') ? 'active' : '' }}">
                        <i class="icon-bookmark"></i>
                        <span class="font">
                            ข้อมูลรถที่สนใจ
                        </span>
                        @if(wishlist_count() != 0)
                            <span class="badge bg-danger-400 align-self-center ml-auto"> {{ wishlist_count() }} </span>
                        @endif
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('interested.index') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'interested') ? 'active' : '' }}">
                        <i class="icon-star-full2"></i>
                        <span class="font">
                            รายการที่สนใจ
                        </span>
                        @if(interested_count() != 0)
                            <span class="badge bg-danger-400 align-self-center ml-auto"> {{ interested_count() }} </span>
                        @endif
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('contact.index') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'contact') ? 'active' : '' }}">
                        <i class="icon-list"></i>
                        <span class="font">
                            รายการที่ติดต่อ
                        </span>
                        @if(contact_count() != 0)
                            <span class="badge bg-danger-400 align-self-center ml-auto"> {{ contact_count() }} </span>
                        @endif
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('profile.index') }}" class="nav-link {{ Str::startsWith(Request::route()->getName(), 'profile') ? 'active' : '' }}">
						<i class="icon-profile"></i>
						<span class="font">
						 โปรไฟล์
						</span>
					</a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link" onclick="event.preventDefault();document.getElementById('logout-form-menu').submit();">
                        <form action="{{ route('logout') }}" id="logout-form-menu" method="POST">
                            @csrf
                        </form>
						<i class="icon-switch2"></i> <span class="font"> ออกจากระบบ </span>
					</a>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/template/navbar.blade.php
<div class="navbar navbar-expand-md navbar-dark">
    <div class="navbar-brand">
        <a href="{{ route('dashboard') }}" class="d-inline-block white">
            <img src="/images/logo-text.png" alt="">
        </a>
    </div>
    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-mobile">
        <span class="navbar-text ml-md-3 mr-md-auto">
            {{-- <span class="badge bg-success"> Online </span> --}}
        </span>
        <ul class="navbar-nav">
            @if(wishlist_count() != 0)
            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown"
                    aria-expanded="false">
                    <i class="icon-bookmark"></i>
                    <span class="badge badge-pill bg-warning-400 ml-auto ml-md-0"> {{ wishlist_count() }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                    <div class="dropdown-content-body dropdown-scrollable">
                        <ul class="media-list">
                            @foreach (wishlist_new() as $k => $item)
                            @if($k != 0)
                            <hr>
                            @endif
                            <li class="media font">
                                <div class="media-body">
                                    <div class="media-title">
                                        <span class="font-weight-semibold">
                                            {{ $item->brand }} {{ $item->model }}  {{ $item->year }}  {{ $item->gear }}
                                        </span>
                                    </div>
                                    <span class="text-muted">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> ชื่อ </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ $item->name  }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> เบอร์โทร </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ $item->tel  }} </p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> วัน/เวลา </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ date_thai($item->created_at, TRUE) }} </p>
                                            </div>
                                        </div>
                                    </span>
                                </div>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="dropdown-content-footer justify-content-center p-0">
                        <a href="{{ route('wishlist.index') }}" class="bg-light text-grey w-100 py-2">
                            <span class="text-center d-block top-0 font"> ข้อมูลรถที่สนใจทั้งหมด </span>
                        </a>
                    </div>
                </div>
            </li>
            @endif
            @if(interested_count() != 0)
            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown"
                    aria-expanded="false">
                    <i class="icon-star-full2"></i>
                    <span class="badge badge-pill bg-warning-400 ml-auto ml-md-0"> {{ interested_count() }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                    <div class="dropdown-content-body dropdown-scrollable">
                        <ul class="media-list">
                            @foreach (interested_new() as $k => $item)
                            @if($k != 0)
                            <hr>
                            @endif
                            <li class="media font">
                                <div class="media-body">
                                    <div class="media-title">
                                        <span class="font-weight-semibold">
                                            <a href="{{ route('car.show', $item->CarEvaID) }}">
                                                {{ $item->cars['CarBrandName'] }} {{ $item->cars['CarBrandGenName'] }}
                                            </a>
                                        </span>
                                        <span class="text-muted float-right">
                                            {{ date_thai($item->created_at, TRUE) }}
                                        </span>
                                    </div>
                                    <span class="text-muted">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> ชื่อ </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ $item->Name  }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> เบอร์โทร </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ $item->Phone  }} </p>
                                            </div>
                                        </div>
                                    </span>
                                </div>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="dropdown-content-footer justify-content-center p-0">
                        <a href="{{ route('interested.index') }}" class="bg-light text-grey w-100 py-2">
                            <span class="text-center d-block top-0 font"> รายการที่สนใจทั้งหมด </span>
                        </a>
                    </div>
                </div>
            </li>
            @endif
            @if(contact_count() != 0)
            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown"
                    aria-expanded="false">
                    <i class="icon-bell3"></i>
                    <span class="badge badge-pill bg-warning-400 ml-auto ml-md-0"> {{ contact_count() }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                    <div class="dropdown-content-body dropdown-scrollable">
                        <ul class="media-list">
                            @foreach (contact_unread() as $k => $item)
                            @if($k != 0)
                            <hr>
                            @endif
                            <li class="media font">
                                <div class="media-body">
                                    <div class="media-title">
                                        <a href="{{ route('contact.show', $item->id) }}">
                                            <span class="font-weight-semibold">
                                                {{ substr($item->detail, 0, 20).'...'  }}
                                            </span>
                                            <span class="text-muted float-right">
                                                {{ date_thai($item->created_at, TRUE) }}
                                            </span>
                                        </a>
                                    </div>
                                    <span class="text-muted">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> ผู้ติดต่อ </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ $item->first_name  }} {{ $item->last_name  }} </p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong> เบอร์โทร </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <p> {{ $item->tel  }} </p>
                                            </div>
                                        </div>
                                    </span>
                                </div>
                            </li>
                            @endforeach
                        </ul>
                    </div>

                    <div class="dropdown-content-footer justify-content-center p-0">
                        <a href="{{ route('contact.index') }}" class="bg-light text-grey w-100 py-2">
                            <span class="text-center d-block top-0 font"> รายการที่ติดต่อทั้งหมด </span>
                        </a>
                    </div>
                </div>
            </li>
            @endif
            <li class="nav-item dropdown dropdown-user">
                <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src="/images/user.png" alt="" class="rounded-circle" width="35">
                    <span> {{ Auth::user()->name }} </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right font">
                    <a href="{{ route('profile.index') }}" class="dropdown-item"><i class="icon-profile"></i> โปรไฟล์
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item font"
                        onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="icon-switch2"></i> ออกจากระบบ </a>
                    <form action="{{ route('logout') }}" id="logout-form" method="POST">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
    </div>
</div>